ALL_VALID: no

DESCRIPTION_KEYWORDS_I:
- privilege escalation
- escalation
- privesc
- high integrity
- elevated privilege
- escalation of privilege
- " sudo "
- " suid "
- " pe "
- " UAC "
- User Account Control
- linpeas
- winpeas
- docker
- kubernetes
- " lxc "
- podman

DESCRIPTION_KEYWORDS:
- ThisIsACaseSensitiveExample

PRODUCT_KEYWORDS_I:
- sudo
- kubernetes
- lxc
- Fortinet
- GLPI
- PaloAlto
- Ubuntu
- Windows
- Checkpoint
- Defender
- Office
- Azure
- Intune
- Microsoft

PRODUCT_KEYWORDS:
- ThisIsACaseSensitiveExample

